format = "$directory$all"

[kubernetes]
disabled = false
format = '\([⎈](bold fg:33)[$cluster](fg:166):[$namespace](dimmed green)\) '

[aws]
disabled = false
force_display = true
style = 'yellow'

[python]
disabled = false

[battery]
disabled = false
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[lua]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = '🌐 '
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.payoneer.com'
disabled = false
